### ISSUE TITLE
Cant install in laravel 5.5

### ISSUE THREAD

**Issue by Kokil** [antonioribeiro/health#105]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: phpunit/php-timer[2.0.0, 1.0.9].
    - Can only install one of: phpunit/php-timer[2.0.0, 1.0.9].
    - Can only install one of: phpunit/php-timer[2.0.0, 1.0.9].
    - pragmarx/health v0.9.9 requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0].
    - Installation request for pragmarx/health ^0.9.9 -> satisfiable by pragmarx/health[v0.9.9].
    - Installation request for phpunit/php-timer (locked at 1.0.9) -> satisfiable by phpunit/php-timer[1.0.9].

**Comment by mhipo1364** [comment]
You need to update your `phpunit` in your `--dev` stage. I mean, `php-timer` is not on satisfiable verison. Run this command:

    composer require --dev phpunit/phpunit --update-with-dependencies

Then install `health` package.

**Comment by antonioribeiro** [comment]
Pushed some fixes to make it work on Laravel 5.5: https://travis-ci.org/antonioribeiro/health

![image](https://user-images.githubusercontent.com/3182864/45920313-9205b280-be78-11e8-9995-79a08cc03f5c.png)
