### ISSUE TITLE
Not work on Laravel 5.7

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [antonioribeiro/health#106]

**Comment by antonioribeiro** [comment]
I'm using it in two different Laravel 5.7 apps, what's your error message?

**Comment by MahdiMajidzadeh** [comment]
first couple times not work but in next try it's took 8 min to run!
is it normal?

**Comment by antonioribeiro** [comment]
Not normal, but there are some resource which can make it take a lot of time. If you enable database and charts, it should show you the time each one is taking.

![image](https://user-images.githubusercontent.com/3182864/45918578-6f1ad480-be5f-11e8-98c8-e7a9ea9f7620.png)

As you can see above, it takes 16 seconds to check for outdated packages here.

**Comment by antonioribeiro** [comment]
Closing for now. Ask to reopen if you find any problems, right.

**Comment by antonioribeiro** [comment]
Disable notifications, it must be trying to send e-mails, and, if queues are disabled, it may take a lot of time when your mail server is not correctly configure.
