### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by 1benayatei** [antonioribeiro/health#107]
Error 404 when open route health/panel.

![capture](https://user-images.githubusercontent.com/20650109/45866448-19c6c080-bd96-11e8-9092-c9e1aa1d5fd0.PNG)
**ّFor what ?**

**Comment by antonioribeiro** [comment]
Please, check if those routes are up

```

php artisan route:list | grep health
```

**Comment by CodeCooler** [comment]
Ensure you're not caching routes and/or configurations:

`php artisan config:clear`
`php artisan route:clear`

or 

`php artisan optimize`

Worked for me!
