### ISSUE TITLE
Documentation - add notice to check the location of binaries

### ISSUE THREAD

**Issue by JustinGT** [antonioribeiro/health#108]
In the .yml files you have

~~~yml
name: Latency
.
.
.
binary: /sbin/ping
.
.
.
~~~

Depending upon you os flavour, it may not be in that folder:
~~~bash
health.test$ which ping
/bin/ping
~~~

So if you could make a note telling people to check that, it would probably save some of the "Its not working" issues!

**Comment by antonioribeiro** [comment]
Okay, thanks for reporting. Added a way to configure binaries via .env, since our local dev and production may differ:

    'services' => [
        'ping' => [
            'bin' => env('HEALTH_PING_BIN', '/sbin/ping'),
        ],

        'composer' => [
            'bin' => env('HEALTH_COMPOSER_BIN', 'composer'),
        ],
    ],
