### ISSUE TITLE
Livereload ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by robsontenorio** [antonioribeiro/health#121]
Where does it "livereload.js" come from? There is no reference on source code.

Is there any additional instruction to solve this problem?

NOTE: Laravel Health package was installed on project running with docker. 

![captura de tela 2018-10-03 as 00 13 03](https://user-images.githubusercontent.com/118955/46388186-26ee8400-c6a1-11e8-8523-b8fb88ac3b2a.png)

**Comment by antonioribeiro** [comment]
This happens only if your APP_ENV = local, important for those developing health stuff.

If you run `npm install` and `npm run watch`, LiveReload should boot fine.

Livereload will reload your page every time your assets change.
