### ISSUE TITLE
Support for Laravel 5.8

### ISSUE THREAD

**Issue by tenshiAMD** [antonioribeiro/health#146]
@antonioribeiro, I was looking for a health check mechanism and found this repository ... I also hoping for this package will have support for Laravel 5.8 ... Thanks in advance 🎉

**Comment by drbyte** [comment]
Update: It appears to support L5.8 now.
https://github.com/antonioribeiro/health/commit/1f080d7a4d123a322a057d627c28c57ec7eb9b5c

**Comment by tenshiAMD** [comment]
Thanks for the info @drbyte ~! 🎉
