### ISSUE TITLE
Cannot see charts

### ISSUE THREAD

**Issue by sebhmg** [antonioribeiro/health#148]
Hi,
with Laravel 5.5, and using the latest release version of Health, or the master branch, I cannot see the charts on the buttons. Is there extra things to install or configure to see charts?
Some minimum required versions for `vue` or `laravel-mix`?
Thanks

**Comment by pkatuwal** [comment]
First Create Table "health_checks"

Enable config/health.php 
database=>true,
'graphs' => [
            'enabled' => true,

            'height' => 90,
        ],

Thanks

**Comment by sebhmg** [comment]
Enabling database in the config solved it. Thanks!
