### ISSUE TITLE
Package is ignoring APP_URL

### ISSUE THREAD

**Issue by lostdesign** [antonioribeiro/health#173]
So my `APP_URL` is `http://localhost/laravel/` - when I visit `http://localhost/laravel/health/panel` I can see that health is making requests to `http://localhost/health/resources` which cannot be resolved. I was digging for the reason of this but could not find a solution.

When I visit `http://localhost/laravel/health/resources` myself, I do get the data returned. So why is it that the panel is making requests without `/laravel`?

Note: On package setup the APP_URL wasn't /laravel, I changed it afterwards. 
It's weird that I can actually goto each routes, but the panel requesting something different. 

Cache has been cleared, my laravel version is: `"laravel/framework": "^6.2",`

**Comment by antonioribeiro** [comment]
You probably have to update the prefix:

![image](https://user-images.githubusercontent.com/3182864/89102495-18429680-d40a-11ea-8664-10a03c86084b.png)
