### ISSUE TITLE
Support phpunit/php-timer 3.0.0

### ISSUE THREAD

**Issue by krns** [antonioribeiro/health#175]
This packages does not support the newest major version of `phpunit/php-timer`. 

For example phpunit 9 requires [`"phpunit/php-timer": "^3.0"`](https://github.com/sebastianbergmann/phpunit/blob/master/composer.json#L41) and this packages does [not support this version](https://github.com/antonioribeiro/health/blob/master/composer.json#L26), which can cause problems.

**Comment by DecortDev** [comment]
Same issue here

**Comment by krns** [comment]
Btw this is needed when using phpunit 9, which depends on php-timer 3

**Comment by krns** [comment]
Meanwhile the newest version of phpunit required [`"phpunit/php-timer": "^4.0"`](https://github.com/sebastianbergmann/phpunit/blob/master/composer.json#L41)...

**Comment by zolotov88** [comment]
Meanwhile the newest version of phpunit required "phpunit/php-timer": "^5.0"...

**Comment by antonioribeiro** [comment]
Supporting from 1 to 5 now.
