### ISSUE TITLE
Type Error issue with latest Laravel 7.x 

### ISSUE THREAD

**Issue by ssmusoke** [antonioribeiro/health#183]
Due to this PR https://github.com/laravel/framework/pull/33539, the package throws an error 

` TypeError

Illuminate\Container\Container::bind(): Argument #2 ($concrete) must be of type Closure|string|null

at vendor/laravel/framework/src/Illuminate/Container/Container.php:238
234| // bound into this container to the abstract type and we will just wrap it
235| // up inside its own Closure to give us more convenience when extending.
236| if (! $concrete instanceof Closure) {
237| if (! is_string($concrete)) {

238| throw new \TypeError(self::class.'::bind(): Argument #2 ($concrete) must be of type Closure|string|null');
239| }
240|
241| $concrete = $this->getClosure($abstract, $concrete);
242| }

  +10 vendor frames 
11 artisan:37
Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
`

**Comment by AustinW** [comment]
Getting the same issue as described here. Will try to submit a PR later if still unresolved.

**Comment by Stefan-Dressler** [comment]
I am also waiting for this fix.

**Comment by vvanpo** [comment]
Considering Laravel just released a security vulnerability fix (https://blog.laravel.com/security-release-laravel-61827-7220), this is blocking projects from integrating this fix.

**Comment by vvanpo** [comment]
The bug is right here: https://github.com/antonioribeiro/health/blob/master/src/ServiceProvider.php#L320. This needs to be a closure.
