### ISSUE TITLE
[Laravel version:8.11.2] DomainException : Invalid value for config('health.resources.enabled'') when trying to publish config and views

### ISSUE THREAD

**Issue by amdadulhoque** [antonioribeiro/health#235]

**Comment by amdadulhoque** [comment]
@antonioribeiro  Can you please suggest me if there is any solution for publish config and views?

**Comment by metrapk** [comment]
Try deleting cache files from  your bootstrap/cache directory   and run "composer dump-autoload"

Should let you run the publish after that

**Comment by amdadulhoque** [comment]
@metrapk thanks for reply. Found the cache issue later but forgot to close this issue.
