### ISSUE TITLE
Error on Database User for different namespace than App

### ISSUE THREAD

**Issue by evertramos** [antonioribeiro/health#3]
Hi there,

I am receiving the message below and I do have the class User under app/User.php (model):

![sem titulo](https://cloud.githubusercontent.com/assets/905951/20724113/237817b4-b654-11e6-8c49-ac0a959fde5f.png)

**Comment by antonioribeiro** [comment]
Is your root namespace App?
Have you tried to tweak the config?

**Comment by antonioribeiro** [comment]
The related configuration you need to change is this one, if 

![image](https://cloud.githubusercontent.com/assets/3182864/20792998/faf8db1c-b7ab-11e6-9073-38feb822cc2d.png)

And not only

![image](https://cloud.githubusercontent.com/assets/3182864/20793019/21e0fe8a-b7ac-11e6-8844-4bccc2e7e295.png)
