### ISSUE TITLE
Error on ssl check

### ISSUE THREAD

**Issue by evertramos** [antonioribeiro/health#4]
Hi there, 

My ssl is working fine and still get the message below, please note says "httpSS":

![sem titulo](https://cloud.githubusercontent.com/assets/905951/20724179/5dad7500-b654-11e6-892c-22f6567726c1.png)

**Comment by excellentingenuity** [comment]
Same here...

**Comment by antonioribeiro** [comment]
Should be fixed by https://github.com/antonioribeiro/health/commit/01acaa2f36334a4d84689f930b8a6575a78b2f40.

Thank you!
