### ISSUE TITLE
Health status fails when Cache (Redis) is down

### ISSUE THREAD

**Issue by tylermauthe** [antonioribeiro/health#40]
This will return 500, so your Envoyer health checks / etc will pick it up -- however I think it could be handled more gracefully. It also stops the email notices from going out because the console checks fail before generating an email. Slack is also probably stopped, though I didn't test this.

Perhaps if a connection to the cache cannot be made, the cache layer should be ignored and health checks should go directly to the service they check and not write their response to the cache.

Thoughts?

**Comment by antonioribeiro** [comment]
Yeah, that should not happen, it is supposed to be as failsafe as it can possibily be. I'll take a look at it. Thank you!

**Comment by tylermauthe** [comment]
No, thank you! It's a really great library. Please let me know if there's anything I can do to assist.

**Comment by antonioribeiro** [comment]
Should be fixed by
https://github.com/antonioribeiro/health/commit/fe5f2638396112174b4c736a0a004811c414da40

**Comment by tylermauthe** [comment]
Thanks! The command line panel runs and the health status page shows a red tile. Good stuff, dang exceptions.
