### ISSUE TITLE
Symfony/yaml should be required not required --dev

### ISSUE THREAD

**Issue by andreipetcu** [antonioribeiro/health#61]
Trying to deploy a project using this package in production with 'composer install --no-dev' resulted in 
> production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Symfony\Component\Yaml\Yaml' not found in ./vendor/pragmarx/health/src/Support/Yaml.php:37

Moving symfony/yaml to "required" would fix this issue.

**Comment by antonioribeiro** [comment]
Should not be required at all, since it uses pragmarx/yaml, which requires symfony/yaml, but thanks.
