### ISSUE TITLE
Redis check failing from code issues

### ISSUE THREAD

**Issue by adrian-tilita** [antonioribeiro/health#62]
Currently, for Redis check, I get:
`Non-static method Redis::set() cannot be called statically`

My environment:
- Laravel v5.4.36
- PHP 7.1.6

For my environment, the fix is actually quite simple. Based on documentation from https://laravel.com/docs/5.4/redis#interacting-with-redis the fix is just a proper "use" namespace.

Basically, from:
```<?php
namespace PragmaRX\Health\Checkers;

use Redis;

class RedisChecker extends BaseChecker
{ // rest of the code
```
I would change to:
```
<?php
namespace PragmaRX\Health\Checkers;

use Illuminate\Support\Facades\Redis;

class RedisChecker extends BaseChecker
{ // rest of the code
```

If it's ok, I will submit a pull-request, but, at first, please confirm that the issue can be reproduced in other environments.

**Comment by antonioribeiro** [comment]
Done in all façades, thanks!
