### ISSUE TITLE
Can't install in Laravel 5.4

### ISSUE THREAD

**Issue by jrodri2001** [antonioribeiro/health#66]
According to Documentation, that this can be installed in Laravel 5.3+, however, composer fails with the following message:

`Problem 1
    - Installation request for pragmarx/health ^0.4.0 -> satisfiable by pragmarx/health[v0.4.0].
    - pragmarx/health v0.4.0 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev, v5.5.0, v5.5.1, v5.5.10, v5.5.11, v5.5.12, v5.5.13, v5.5.14, v5.5.15, v5.5.16, v5.5.17, v5.5.18, v5.5.19, v5.5.2, v5.5.20, v5.5.21, v5.5.22, v5.5.23, v5.5.24, v5.5.25, v5.5.26, v5.5.27, v5.5.3, v5.5.4, v5.5.5, v5.5.6, v5.5.7, v5.5.8, v5.5.9] but these conflict with your requirements or minimum-stability.`

Please let me know if this can be installed in Laravel 5.4. Thanks.

**Comment by mmehdibalouchi** [comment]
I have the same issue

**Comment by marktopper** [comment]
`v0.4.0` request Laravel 5.5
