### ISSUE TITLE
resources_enabled list

### ISSUE THREAD

**Issue by rap2hpoutre** [antonioribeiro/health#70]
In the `resources_enabled` config key (`config/health.php` file), the comment says:

> use an array to select some

I don't know where is the list of available values.

**Comment by Qsick** [comment]
You can find the default ones here:

https://github.com/antonioribeiro/health/tree/master/src/config/resources

Just drop the .yml when listing in your array.

**Comment by marktopper** [comment]
You can use those options:
https://github.com/antonioribeiro/health/blob/master/src/Support/Constants.php

**Comment by antonioribeiro** [comment]
Moved it to an array of regexes.
