### ISSUE TITLE
404 for /health/resource/{name}

### ISSUE THREAD

**Issue by Qsick** [antonioribeiro/health#71]
The route for /health/resource/{name} doesn't seem to be working for me and I get a 404.  I have tried the name and the abbreviation for {name} and can't seem to get it to work.  Is there additional configuration I'm missing?

**Comment by handrej** [comment]
Change the resource route to `'uri' => $route_prefix.$route_suffix_resource."/{name}"` in your config `health.php`, or else it will register the wrong route (`health./resource/{name}`)
