### ISSUE TITLE
Error parsing Queue.yml file

### ISSUE THREAD

**Issue by ngugijames** [antonioribeiro/health#73]
I get the following error after installation 
In Parser.php line 343:
                                                                        
  Duplicate key "name" detected at line 3 (near "name: health-queue"). 

It seems this file -> https://github.com/antonioribeiro/health/blob/v0.3.2/src/config/resources/Queue.yml has a duplicate entry for the `name` key

**Comment by antonioribeiro** [comment]
Sorry about that and the delay. But it is fixed.
