### ISSUE TITLE
Class {{ config('auth.providers.users.model') }} does not exist

### ISSUE THREAD

**Issue by jmauerhan** [antonioribeiro/health#80]
Upon a fresh install, I followed the directions, and the Database check fails with this error. There's no documentation on what this class should be.

**Comment by mohrajab** [comment]
The same issue here, @jmauerhan do you find the solution?

**Comment by mohrajab** [comment]
Aha, I think it's just a label. I change the value of YAML file of Database
from {{ config('auth.providers.users.model') }}
to App\\Models\\User

And it's run successfully

**Comment by poor-bob** [comment]
I use this package in a Docker image, so we need to be able to replicate the build process every time programmatically. 

Here's what I run in my Dockerfile
`RUN sed -i '6s/.*/    - App\\User/g' /var/www/vendor/pragmarx/health/src/config/resources/Database.yml`
