### ISSUE TITLE
Installation failed on Laravel 5.6

### ISSUE THREAD

**Issue by pavinthan** [antonioribeiro/health#81]
```pragmarx/health suggests installing docusign/esign-client (^2.0)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Parser.php line 343:
                                                                        
  Duplicate key "name" detected at line 3 (near "name: health-queue").  
                                                                        

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1```

**Comment by skydiver** [comment]
You need to remove `name: Queue` (first line) in `vendor/pragmarx/health/src/config/resources/Queue.yml`

**Comment by bingalls** [comment]
According to their composer.json specs, newer versions of Health only work on Laravel v5.5 (dev-master, v4.0.0). However, the older v3.3 allows Laravel 5.6 (!)

**Comment by MNV** [comment]
The newest version of extension is v0.4.0 and it doesn't support Laravel 5.6. Have you planned to add Laravel 5.6 version in future releases?

**Comment by poor-bob** [comment]
I use this library in a Docker image so I have to fix the package every time I re build. Here's the command I use in my Dockerfile
`RUN sed -i '3d' /var/www/vendor/pragmarx/health/src/config/resources/Queue.yml`

**Comment by antonioribeiro** [comment]
Should work in 5.6 and 5.7 as soon as I tag a new version.

**Comment by pavinthan** [comment]
Thanks Guys.
